export const ADD_METRIC_RESULTS = 'ADD_METRIC_RESULTS';
export const ADD_SOURCE = 'ADD_SOURCE';
export const REMOVE_SOURCE = 'REMOVE_SOURCE';
export const SIGN_IN_PROFILE = 'SIGN_IN_PROFILE';
export const SIGN_UP_PROFILE = 'SIGN_UP_PROFILE';
export const SIGN_OUT_PROFILE = 'SIGN_OUT_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const RECEIVE_AUTH = 'RECEIVE_AUTH';

export const SET_FETCHED_ALREADY = 'SET_FETCHED_ALREADY';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';

export const FETCH_SIGN_UP_FAILURE = 'FETCH_SIGN_UP_FAILURE';
export const FETCH_SIGN_UP_REQUEST = 'FETCH_SIGN_UP_REQUEST';
export const FETCH_SIGN_UP_SUCCESS = 'FETCH_SIGN_UP_SUCCESS';

export const FETCH_SIGN_OUT_FAILURE = 'FETCH_SIGN_OUT_FAILURE';
export const FETCH_SIGN_OUT_REQUEST = 'FETCH_SIGN_OUT_REQUEST';
export const FETCH_SIGN_OUT_SUCCESS = 'FETCH_SIGN_OUT_SUCCESS';

export const FETCH_SIGN_IN_FAILURE = 'FETCH_SIGN_IN_FAILURE';
export const FETCH_SIGN_IN_REQUEST = 'FETCH_SIGN_IN_REQUEST';
export const FETCH_SIGN_IN_SUCCESS = 'FETCH_SIGN_IN_SUCCESS';


export const AUTH_INPUT = 'AUTH_INPUT';
