export const ADD_METRIC_RESULTS = 'ADD_METRIC_RESULTS';
export const ADD_SOURCE = 'ADD_SOURCE';
export const REMOVE_SOURCE = 'REMOVE_SOURCE';
export const SIGN_IN_PROFILE = 'SIGN_IN_PROFILE';
export const SIGN_OUT_PROFILE = 'SIGN_OUT_PROFILE';

export const SET_FETCHED_ALREADY = 'SET_FETCHED_ALREADY';
