export const ADD_METRIC_RESULTS = 'ADD_METRIC_RESULTS';
export const ADD_SOURCE = 'ADD_SOURCE';
export const REMOVE_SOURCE = 'REMOVE_SOURCE';
export const SIGN_IN_PROFILE = 'SIGN_IN_PROFILE';
export const SIGN_UP_PROFILE = 'SIGN_UP_PROFILE';
export const SIGN_OUT_PROFILE = 'SIGN_OUT_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const RECEIVE_AUTH = 'RECEIVE_AUTH';

export const SET_FETCHED_ALREADY = 'SET_FETCHED_ALREADY';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';

export const FETCH_SIGN_UP_FAILURE = 'FETCH_SIGN_UP_FAILURE';
export const FETCH_SIGN_UP_REQUEST = 'FETCH_SIGN_UP_REQUEST';
export const FETCH_SIGN_UP_SUCCESS = 'FETCH_SIGN_UP_SUCCESS';

export const FETCH_SIGN_OUT_FAILURE = 'FETCH_SIGN_OUT_FAILURE';
export const FETCH_SIGN_OUT_REQUEST = 'FETCH_SIGN_OUT_REQUEST';
export const FETCH_SIGN_OUT_SUCCESS = 'FETCH_SIGN_OUT_SUCCESS';

export const FETCH_SIGN_IN_FAILURE = 'FETCH_SIGN_IN_FAILURE';
export const FETCH_SIGN_IN_REQUEST = 'FETCH_SIGN_IN_REQUEST';
export const FETCH_SIGN_IN_SUCCESS = 'FETCH_SIGN_IN_SUCCESS';

export const FETCH_LYFT_TOKEN_REQUEST = 'FETCH_LYFT_TOKEN_REQUEST';
export const FETCH_LYFT_TOKEN_SUCCESS = 'FETCH_GET_TOKEN_SUCCESS';
export const FETCH_LYFT_TOKEN_FAILURE = 'FETCH_LYFT_TOKEN_FAILURE';

export const FETCH_METRICS_REQUEST = 'FETCH_METRICS_REQUEST';
export const FETCH_METRICS_SUCCESS = 'FETCH_METRICS_SUCCESS';
export const FETCH_METRICS_FAILURE = 'FETCH_METRICS_FAILURE';

export const FETCH_YELP_REQUEST = 'FETCH_YELP_REQUEST';
export const FETCH_YELP_SUCCESS = 'FETCH_YELP_SUCCESS';
export const FETCH_YELP_FAILURE = 'FETCH_YELP_FAILURE';

export const SET_YELP = 'SET_METRICS';

export const SET_METRICS = 'SET_METRICS';

export const AUTH_INPUT = 'AUTH_INPUT';
